const express = require('express');
const router = express.Router();
const userController = require('../controllers/usercontroller');
router.post('/signup', userController.signup);
router.post('/email',userController.email);
router.post('/oauth', userController.OAuth);
router.post('/login', userController.login);
router.post('/logout', userController.logout);
router.post('/tokenexpired',userController.verifyToken);
module.exports = router;
